// frontend/src/views/HomePage.vue
<template>
  <div class="home">
    <h2>Auto Project</h2>
    <p class="subtitle">AI-driven full-stack application powered by WorkBuddy</p>
    <el-row :gutter="20" class="cards">
      <el-col :span="8">
        <el-card>
          <template #header><span>前端</span></template>
          <p>Vue 3 + Element Plus + Vite + TypeScript</p>
        </el-card>
      </el-col>
      <el-col :span="8">
        <el-card>
          <template #header><span>后端</span></template>
          <p>Spring Boot 3.4 + Java 21 + MyBatis-Plus</p>
        </el-card>
      </el-col>
      <el-col :span="8">
        <el-card>
          <template #header><span>流水线</span></template>
          <p>每日 02:00 自动开发循环</p>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<style scoped>
.home {
  text-align: center;
  padding: 60px 20px;
}
.subtitle {
  color: var(--el-text-color-secondary);
  margin-bottom: 40px;
}
.cards {
  max-width: 900px;
  margin: 0 auto;
}
</style>

// frontend/src/pages/HomePage.tsx
export default function HomePage() {
  return (
    <div className="flex flex-col items-center justify-center py-16">
      <h2 className="text-3xl font-bold tracking-tight">Auto Project</h2>
      <p className="mt-4 text-muted-foreground">
        AI-driven full-stack application powered by WorkBuddy
      </p>
      <div className="mt-8 flex gap-4">
        <div className="rounded-lg border bg-card p-6 text-center">
          <p className="text-sm font-medium">Frontend</p>
          <p className="mt-1 text-xs text-muted-foreground">React 19 + Vite + Tailwind CSS</p>
        </div>
        <div className="rounded-lg border bg-card p-6 text-center">
          <p className="text-sm font-medium">Backend</p>
          <p className="mt-1 text-xs text-muted-foreground">Spring Boot + Java 21 + MyBatis-Plus</p>
        </div>
        <div className="rounded-lg border bg-card p-6 text-center">
          <p className="text-sm font-medium">Pipeline</p>
          <p className="mt-1 text-xs text-muted-foreground">Daily 02:00 auto dev cycle</p>
        </div>
      </div>
    </div>
  )
}
